### ISSUE TITLE
Weapon Accuracy adds random spread

### ISSUE THREAD

**Issue by Lorithan** [jfilm/zombie-time#1]
Currently weapons have an unused field, `accuracy`. It was my intent to have this be a number between 0.0 and 1.0 that helps determine bullet spread. 1.0 means that the bullet goes exactly where you cursor is, while 0.0 means the bullet could go anywhere else.

**Comment by kornatskyi** [comment]
Did it, but accuracy is working the opposite way, 0 is maximum accuracy and >=1 is totally random

**Comment by Lorithan** [comment]
I'd prefer we'd do it the opposite way, and it should be trivial to reverse it, but it's a trivial matter. Feel free to close the issue

**Comment by kornatskyi** [comment]
Ok, I'll do this the way you want. I did it the opposite way because it was easier for me at that point.
