### ISSUE TITLE
Weapon Rate of Fire and automatic

### ISSUE THREAD

**Issue by Lorithan** [jfilm/zombie-time#2]
Can add a new field called Rate of Fire that could determine how fast different guns can fire. If feeling adventurous, we could set up work for a way to allow "automatic" weapons that will keep firing while the mouse is down, as oppose to having to click for each shot.

**Comment by kornatskyi** [comment]
Done

**Comment by kornatskyi** [comment]
The issue with an array that passes through pullTrigger() method to the shoot() method. If we use the shoot() in setIterval()'s callback then it cant reach the upper scope array.

**Comment by kornatskyi** [comment]
Now it works properly
